# -*- coding: utf-8 -*-
"""ATM_Classs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LFZO9LRl_4mZC_WQjrKXfsKQnRXNi0lV

# ATM Class
- information
- deposit cash
- withdraw
- balance
- open a new saving acc.
"""

class ATM:
    def __init__(self):
        self.name = ""
        self.acc_no = ""
        self.pin = ""
        self.balance = 0
        while True:
            user = int(input(f"""Please select:
                    [1] Open a new saving account
                    [2] See my information
                    [3] deposit cash
                    [4] withdraw
                    [5] balance check
                    [6] exit
                    """))
            
            if user < 1 or user > 6:
                print("Wrong enter, Please try select!")
                continue

            if user == 1:
                self.open_acc()
            elif user == 2:
                self.information()
            elif user == 3:
                self.deposit()
            elif user == 4:
                self.withdraw()
            elif user == 5:
                self.balance_check()
            else:
                print("Thank you!")
                break

    def __str__(self):
        return "Welcome to the Rick bank _/\_"

    def information(self):
        print(f"""
            Account Name: {self.name}
            Account No.: {self.acc_no}
            Balance: {self.balance} THB
            """)

    def deposit(self):
        dep_user = int(input("Deposit amount: "))
        self.balance += dep_user
        print(f"""
            +++++++++ Deposit Successful +++++++++
            >> Balance: {self.balance} THB <<
            """)
        
    def withdraw(self):
        wthd_user = int(input("Withdraw amount: "))
        self.balance -= wthd_user
        print(f"""
            --------- Withdraw Successful ---------
            >> Balance: {self.balance} THB <<
            """)
        
    def transfer(self):
        request = int(input("Please enter the Account No. to transfer: "))
        trans_amnt = int(input("Amount Transfer(THB): "))
        self.balance -= trans_amnt
        print(f"""
            Transferee Account No.: {request}
            Amount: {trans_amnt} THB
            --------- Transfer Successful ---------
            >> Balance: {self.balance} THB <<
            """)

    def balance_check(self):
        print(f"""
            Account Name: {self.name}
            Account No.: {self.acc_no}
            Balance: {self.balance} THB
            """)
        
    def open_acc(self):
        self.name = input("Please enter your Firstname - Lastname: ") 
        self.acc_no = int(input("Please create your account no. (10 digits): "))
        self.pin = input("Please create your pin (6 digits): ")
        self.balance = int(input("Please enter the amount to be deposited(THB): "))

        self.balance_check()

ATM()

while True:
    user = int(input(f"""Please select:
                    [1] 
                    """))

a = 0

def aa():
    return 5

def bb():
    print(5)
    return aa()


a = bb() + aa()

print(a)

bb()

