# -*- coding: utf-8 -*-
"""Rock Paper Scissors.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pHzf59Io1A3QGn61OdmrRZ9Ag7bWGj3y

# Rock Paper Scissors Game
"""

import random
actions =  ["Rock", "Paper", "Scissors", "Exit"]
random_list = ["Rock", "Paper", "Scissors"]

win = 0
loss = 0
tie = 0

while True:
    player = int(input("Choose your move: Rock[1], Paper[2], Scissors[3], Exit[4]: "))
    if player < 1 or player > 4:
        print("Wrong input, please try again!")
        continue
    # if player > 4
    # if player < 1
    # type(player) != int
    if player == 4:
        print(f"""
                See you next time!
                This is your scoreboard
                WIN : TIE : LOSS
                {win} : {tie} : {loss}
            """)
        print(win, tie, loss)
        break
    
    player = actions[player-1]
    computer_ran = random.sample(random_list, k=1)
    computer = computer_ran[0]

    if player == computer:
        tie = tie +1
    elif player == "Rock" and computer == "Paper":
         loss = loss +1
    elif player == "Paper" and computer == "Scissors":
        loss = loss +1
    elif player == "Scissors" and computer == "Rock":
        loss =loss +1
    else:
        win = win+1

    print(f"""
        Player move: {player}
        Computer move: {computer}
        WIN : TIE : LOSS
        {win} : {tie} : {loss}
        """)

